version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    groups:
      pip:
        patterns:
          - "*"
    cooldown:
      default-days: 7
